### PR TITLE
fix: Add shebang to fixup scripts

### LINKED ISSUE #48: scripts/fixup*.py run as shell scripts
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-tasks/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: MaxOS
  - Python version: `python --version` Python 3.7.8
  - pip version: `pip --version` pip 20.1.1
  - `google-cloud-tasks` version: `pip show google-cloud-tasks` 2.0.0

#### Steps to reproduce

  1. Run `fixup_tasks_v2_keywords.py --input-directory .samples/ --output-directory samples/` in terminal, as described in UPGRADING.mst
  2. Observe output below

```
line 18: import: command not found
...
```

#### Code example

None

#### Stack trace

None

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

### PR DESCRIPTION
**Pull request by colincadams**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [X] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-tasks/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #48 🦕

### CODE REVIEW

**Comment by colincadams** [comment]
@googlebot I signed it!

**Review by averikitsch — APPROVED** [review]

**Review by busunkim96 — APPROVED** [review]

**Comment by averikitsch** [comment]
@busunkim96 the error is: `This project needs at least Sphinx v1.6.3 and therefore cannot be built with this version.`

**Comment by busunkim96** [comment]
@averikitsch It looks like the templates in this library were a bit old. I regenerated manually in #34 which also fixed the shebang issue.

**Comment by colincadams** [comment]
Thanks for fixing this!

**Pull request closed without merging**
